version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db
    env_file:
      - ./.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    container_name: frontend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static_value:/usr/share/nginx/html/static/
      - media_value:/usr/share/nginx/html/media/
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      bash -c '
      python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000'
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/usr/share/nginx/html/static/api/
      - media_value:/usr/share/nginx/html/media/api/
    container_name: nginx
    depends_on:
      - backend

volumes:  
  static_value:
  media_value:
  postgres_data:
