version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  # backend:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   volumes:     
  #     - static_value:/app/static/     
  #     - media_value:/app/media/ 
  #   container_name: api 
  #   env_file:
  #     - ../backend/.env
  #   ports:
  #     - "8000:8000"
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:     
      - frontend

volumes:  
  static_value:
  media_value:
