# Generated by Django 2.2.16 on 2022-07-28 08:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220727_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='amount',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
