# Generated by Django 2.2.16 on 2022-07-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='recipe',
        ),
    ]
