# Generated by Django 2.2.16 on 2022-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_ingredientamount_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_amount',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.IngredientAmount', verbose_name='Ингредиенты'),
        ),
    ]
