# Generated by Django 2.2.16 on 2022-07-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_ingredients_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
            preserve_default=False,
        ),
    ]
