# Generated by Django 2.2.16 on 2022-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220729_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='shoping_cart', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
    ]
