# Generated by Django 2.2.16 on 2022-07-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20220729_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcart',
            name='user',
        ),
    ]
