# Generated by Django 2.2.16 on 2022-07-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_shoping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shoping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='recipes.ShopingCart'),
        ),
    ]
